import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SessionProvider } from "next-auth/react";
import { auth } from "@/auth";

import localFont from "next/font/local";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const gilroyExtraLight = localFont({
  src: "../public/gilroy/Gilroy-Thin.ttf",
  variable: "--font-gilroy-extralight",
  display: "swap",
});

const gilroyLight = localFont({
  src: "../public/gilroy/Gilroy-Light.ttf",
  variable: "--font-gilroy-light",
  display: "swap",
});

const gilroyRegular = localFont({
  src: "../public/gilroy/Gilroy-Regular.ttf",
  variable: "--font-gilroy-regular",
  display: "swap",
});

const gilroyMedium = localFont({
  src: "../public/gilroy/Gilroy-Medium.ttf",
  variable: "--font-gilroy-medium",
  display: "swap",
});

const gilroySemibold = localFont({
  src: "../public/gilroy/Gilroy-SemiBold.ttf",
  variable: "--font-gilroy-semibold",
  display: "swap",
});

const gilroyBold = localFont({
  src: "../public/gilroy/Gilroy-Bold.ttf",
  variable: "--font-gilroy-bold",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  const fontClasses = [
    gilroyRegular.variable,
    gilroyLight.variable,
    gilroyExtraLight.variable,
    gilroyMedium.variable,
    gilroySemibold.variable,
    gilroyBold.variable,
  ].join(" ");

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${fontClasses} antialiased font-gilroy-regular flex min-h-screen overflow-y-auto`}
        suppressHydrationWarning={true}
      >
        <SessionProvider session={session}>
          <main className="w-full">{children}</main>
        </SessionProvider>
      </body>
    </html>
  );
}
